<?php

namespace Database\Seeders\Noccea\Learn;

use App\Models\Noccea\Learn\Course;
use Illuminate\Database\Seeder;

class CoursesSeeder extends Seeder
{
    public function run(): void
    {
        // Skip if courses already exist to avoid duplicates
        if (Course::count() > 0) {
            $this->command->info('Courses already exist. Skipping seeder to avoid duplicates.');
            return;
        }

        $courses = [
            [
                'title' => 'Advanced Web Development with React',
                'description' => 'Master React.js and build modern single-page applications with hooks, context API, and performance optimization.',
                'long_description' => 'This comprehensive course covers advanced React concepts including custom hooks, performance optimization, state management, and real-world project development. You\'ll learn best practices for building scalable single-page applications.',
                'category' => 'Web Development',
                'level' => 'Advanced',
                'rating' => 4.8,
                'reviews' => 342,
                'students' => 5420,
                'price' => 0,
                'duration' => '8 weeks',
                'lessons' => 96,
                'image_color' => 'from-blue-500 to-cyan-600',
                'instructor' => 'John Developer',
            ],
            [
                'title' => 'Full Stack Development: MERN Stack',
                'description' => 'Learn MongoDB, Express, React, and Node.js to become a full-stack JavaScript developer.',
                'long_description' => 'Complete guide to becoming a full-stack developer using the MERN stack. Build production-ready applications with database design, API development, authentication, and deployment.',
                'category' => 'Web Development',
                'level' => 'Intermediate',
                'rating' => 4.7,
                'reviews' => 287,
                'students' => 4120,
                'price' => 0,
                'duration' => '10 weeks',
                'lessons' => 120,
                'image_color' => 'from-green-500 to-emerald-600',
                'instructor' => 'Sarah Code',
            ],
            [
                'title' => 'Vue.js 3 Mastery Course',
                'description' => 'Deep dive into Vue.js 3 with composition API, Pinia for state management, and real-world projects.',
                'long_description' => 'Master Vue.js 3 from basics to advanced patterns. Learn the composition API, create reusable components, manage state with Pinia, and build real-world applications.',
                'category' => 'Web Development',
                'level' => 'Intermediate',
                'rating' => 4.6,
                'reviews' => 198,
                'students' => 2980,
                'price' => 0,
                'duration' => '8 weeks',
                'lessons' => 84,
                'image_color' => 'from-emerald-500 to-teal-600',
                'instructor' => 'Mike Frontend',
            ],
            [
                'title' => 'Python Programming for Everyone',
                'description' => 'Start your programming journey with Python. Perfect for beginners with comprehensive examples.',
                'long_description' => 'Learn Python from zero to hero. Perfect for beginners, this course covers programming fundamentals, data structures, functions, and introduces you to libraries for data processing.',
                'category' => 'Programming',
                'level' => 'Beginner',
                'rating' => 4.9,
                'reviews' => 512,
                'students' => 8920,
                'price' => 0,
                'duration' => '6 weeks',
                'lessons' => 72,
                'image_color' => 'from-yellow-500 to-orange-600',
                'instructor' => 'Alex Python',
            ],
            [
                'title' => 'Mobile App Development with Flutter',
                'description' => 'Build cross-platform mobile applications for iOS and Android with Flutter and Dart.',
                'long_description' => 'Create beautiful, native mobile applications for both iOS and Android using Flutter. Learn Dart, design responsive UIs, and deploy your apps to app stores.',
                'category' => 'Mobile Apps',
                'level' => 'Intermediate',
                'rating' => 4.7,
                'reviews' => 234,
                'students' => 3450,
                'price' => 0,
                'duration' => '10 weeks',
                'lessons' => 110,
                'image_color' => 'from-blue-500 to-blue-600',
                'instructor' => 'Diana Mobile',
            ],
            [
                'title' => 'Data Science and Machine Learning',
                'description' => 'Learn data analysis, visualization, and machine learning models with Python.',
                'long_description' => 'Comprehensive course on data science covering pandas, NumPy, scikit-learn, TensorFlow, and visualization tools. Build real-world machine learning models.',
                'category' => 'Data Science',
                'level' => 'Advanced',
                'rating' => 4.8,
                'reviews' => 289,
                'students' => 3890,
                'price' => 0,
                'duration' => '12 weeks',
                'lessons' => 144,
                'image_color' => 'from-purple-500 to-pink-600',
                'instructor' => 'Dr. Science',
            ],
            [
                'title' => 'Cloud Computing with AWS',
                'description' => 'Deploy, manage and scale applications on Amazon Web Services cloud platform.',
                'long_description' => 'Master AWS services including EC2, S3, RDS, Lambda, and more. Learn to architect scalable, secure, and cost-efficient cloud solutions.',
                'category' => 'Cloud Computing',
                'level' => 'Intermediate',
                'rating' => 4.9,
                'reviews' => 298,
                'students' => 4560,
                'price' => 0,
                'duration' => '7 weeks',
                'lessons' => 84,
                'image_color' => 'from-orange-500 to-orange-600',
                'instructor' => 'Cloud Expert',
            ],
            [
                'title' => 'DevOps and CI/CD Pipeline',
                'description' => 'Master continuous integration, deployment, and infrastructure automation.',
                'long_description' => 'Learn DevOps practices, Docker, Kubernetes, Git workflows, and build automated CI/CD pipelines for continuous delivery.',
                'category' => 'DevOps',
                'level' => 'Intermediate',
                'rating' => 4.7,
                'reviews' => 167,
                'students' => 2340,
                'price' => 0,
                'duration' => '8 weeks',
                'lessons' => 96,
                'image_color' => 'from-indigo-500 to-indigo-600',
                'instructor' => 'DevOps Pro',
            ],
            [
                'title' => 'Blockchain and Cryptocurrency',
                'description' => 'Understand blockchain technology, smart contracts, and cryptocurrency development.',
                'long_description' => 'Deep dive into blockchain fundamentals, Ethereum smart contracts, DeFi protocols, and building decentralized applications.',
                'category' => 'Blockchain',
                'level' => 'Advanced',
                'rating' => 4.6,
                'reviews' => 145,
                'students' => 1890,
                'price' => 0,
                'duration' => '10 weeks',
                'lessons' => 105,
                'image_color' => 'from-yellow-600 to-orange-600',
                'instructor' => 'Crypto Dev',
            ],
            [
                'title' => 'UI/UX Design Masterclass',
                'description' => 'Learn modern UI/UX design principles, tools, and create amazing user experiences.',
                'long_description' => 'Master design thinking, wireframing, prototyping, and user research. Learn Figma and create beautiful interfaces.',
                'category' => 'Design',
                'level' => 'Beginner',
                'rating' => 4.8,
                'reviews' => 234,
                'students' => 3120,
                'price' => 0,
                'duration' => '6 weeks',
                'lessons' => 60,
                'image_color' => 'from-pink-500 to-rose-600',
                'instructor' => 'Design Master',
            ],
            [
                'title' => 'Digital Marketing for Beginners',
                'description' => 'Learn digital marketing strategies, SEO, social media, and email marketing.',
                'long_description' => 'Complete guide to digital marketing covering SEO, content marketing, social media strategies, analytics, and paid advertising.',
                'category' => 'Marketing',
                'level' => 'Beginner',
                'rating' => 4.7,
                'reviews' => 178,
                'students' => 2890,
                'price' => 0,
                'duration' => '5 weeks',
                'lessons' => 50,
                'image_color' => 'from-red-500 to-pink-600',
                'instructor' => 'Marketing Pro',
            ],
            [
                'title' => 'Project Management Essentials',
                'description' => 'Master project management methodologies, tools, and leadership skills.',
                'long_description' => 'Learn Agile, Scrum, Kanban methodologies and use tools like Jira. Develop leadership and communication skills.',
                'category' => 'Management',
                'level' => 'Beginner',
                'rating' => 4.6,
                'reviews' => 120,
                'students' => 1560,
                'price' => 0,
                'duration' => '4 weeks',
                'lessons' => 40,
                'image_color' => 'from-green-500 to-teal-600',
                'instructor' => 'PM Master',
            ],
            [
                'title' => 'JavaScript: The Complete Guide',
                'description' => 'Master JavaScript from fundamentals to advanced concepts and asynchronous programming.',
                'long_description' => 'Complete JavaScript course covering ES6+, async/await, promises, DOM manipulation, and modern JavaScript patterns.',
                'category' => 'Programming',
                'level' => 'Beginner',
                'rating' => 4.9,
                'reviews' => 456,
                'students' => 7890,
                'price' => 0,
                'duration' => '8 weeks',
                'lessons' => 96,
                'image_color' => 'from-yellow-500 to-yellow-600',
                'instructor' => 'JS Expert',
            ],
            [
                'title' => 'Database Design and SQL',
                'description' => 'Learn relational database design, normalization, and master SQL queries.',
                'long_description' => 'Comprehensive course on database design principles, SQL fundamentals, advanced queries, and optimization techniques.',
                'category' => 'Databases',
                'level' => 'Intermediate',
                'rating' => 4.7,
                'reviews' => 198,
                'students' => 2650,
                'price' => 0,
                'duration' => '6 weeks',
                'lessons' => 72,
                'image_color' => 'from-blue-600 to-cyan-600',
                'instructor' => 'DB Expert',
            ],
            [
                'title' => 'API Development and REST Services',
                'description' => 'Build RESTful APIs and web services using Node.js and Express.',
                'long_description' => 'Learn REST principles, API design, authentication, versioning, and deploy scalable APIs.',
                'category' => 'Backend',
                'level' => 'Intermediate',
                'rating' => 4.8,
                'reviews' => 212,
                'students' => 3100,
                'price' => 0,
                'duration' => '7 weeks',
                'lessons' => 84,
                'image_color' => 'from-green-500 to-green-600',
                'instructor' => 'API Master',
            ],
            [
                'title' => 'Cybersecurity Fundamentals',
                'description' => 'Learn cybersecurity principles, common threats, and defensive strategies.',
                'long_description' => 'Comprehensive introduction to cybersecurity covering encryption, authentication, network security, and penetration testing basics.',
                'category' => 'Security',
                'level' => 'Intermediate',
                'rating' => 4.6,
                'reviews' => 134,
                'students' => 1780,
                'price' => 0,
                'duration' => '6 weeks',
                'lessons' => 66,
                'image_color' => 'from-red-600 to-red-700',
                'instructor' => 'Security Pro',
            ],
            [
                'title' => 'Artificial Intelligence Basics',
                'description' => 'Introduction to AI concepts, machine learning, and neural networks.',
                'long_description' => 'Explore AI fundamentals, neural networks, deep learning frameworks, and real-world AI applications.',
                'category' => 'AI & ML',
                'level' => 'Intermediate',
                'rating' => 4.8,
                'reviews' => 201,
                'students' => 2340,
                'price' => 0,
                'duration' => '9 weeks',
                'lessons' => 99,
                'image_color' => 'from-purple-500 to-purple-600',
                'instructor' => 'AI Master',
            ],
            [
                'title' => 'Angular Advanced Concepts',
                'description' => 'Master Angular framework with RxJS, dependency injection, and advanced patterns.',
                'long_description' => 'Deep dive into Angular including RxJS observables, dependency injection, routing, forms, and building enterprise applications.',
                'category' => 'Web Development',
                'level' => 'Advanced',
                'rating' => 4.7,
                'reviews' => 156,
                'students' => 2100,
                'price' => 0,
                'duration' => '10 weeks',
                'lessons' => 110,
                'image_color' => 'from-red-500 to-red-600',
                'instructor' => 'Angular Pro',
            ],
            [
                'title' => 'Node.js and Express.js Mastery',
                'description' => 'Build scalable backend applications with Node.js and Express.js framework.',
                'long_description' => 'Complete backend development course using Node.js and Express including databases, authentication, and deployment.',
                'category' => 'Backend',
                'level' => 'Intermediate',
                'rating' => 4.8,
                'reviews' => 267,
                'students' => 3890,
                'price' => 0,
                'duration' => '8 weeks',
                'lessons' => 92,
                'image_color' => 'from-green-600 to-green-700',
                'instructor' => 'Node Master',
            ],
            [
                'title' => 'GraphQL Complete Guide',
                'description' => 'Learn GraphQL query language and build efficient APIs with GraphQL.',
                'long_description' => 'Master GraphQL fundamentals, schema design, queries, mutations, subscriptions, and integration with popular frameworks.',
                'category' => 'Backend',
                'level' => 'Intermediate',
                'rating' => 4.7,
                'reviews' => 145,
                'students' => 1980,
                'price' => 0,
                'duration' => '6 weeks',
                'lessons' => 72,
                'image_color' => 'from-pink-600 to-purple-600',
                'instructor' => 'GraphQL Pro',
            ],
            [
                'title' => 'Docker and Kubernetes',
                'description' => 'Master containerization with Docker and orchestration with Kubernetes.',
                'long_description' => 'Learn Docker fundamentals, Kubernetes orchestration, container networking, and deploy scalable containerized applications.',
                'category' => 'DevOps',
                'level' => 'Intermediate',
                'rating' => 4.7,
                'reviews' => 189,
                'students' => 2670,
                'price' => 0,
                'duration' => '8 weeks',
                'lessons' => 88,
                'image_color' => 'from-blue-600 to-cyan-700',
                'instructor' => 'Container Expert',
            ],
        ];

        foreach ($courses as $course) {
            $slug = strtolower(preg_replace(['/\s+/', '/[^a-zA-Z0-9\-]/'], ['-', ''], $course['title'])) . '-' . (Course::count() + 1);
            $course['slug'] = $slug;
            Course::create($course);
        }

        $this->command->info('Courses seeded successfully!');
    }
}
