<?php

/**
 * KortexTools Configuration
 *
 * Define all available development and productivity tools
 * organized by category
 */

return [
    'tools' => [
        'PDF' => [
            [
                'icon' => 'fas fa-file-pdf',
                'name' => 'Merge PDF',
                'slug' => 'pdf-merge',
                'description' => 'Combine multiple PDF files into one easily.',
                'metaTitle' => 'Merge PDF - KortexTools',
                'metaDescription' => 'Combine multiple PDF files into one easily.',
                'popularity' => 95,
                'rating' => 4.8,
                'rating_count' => 245,
            ],
            [
                'icon' => 'fas fa-file-pdf',
                'name' => 'Split PDF',
                'slug' => 'split-pdf',
                'description' => 'Split a PDF file into separate pages or sections.',
                'metaTitle' => 'Split PDF - KortexTools',
                'metaDescription' => 'Split a PDF file into separate pages or sections.',
                'popularity' => 90,
                'rating' => 4.7,
                'rating_count' => 198,
            ],
            [
                'icon' => 'fas fa-compress',
                'name' => 'Compress PDF',
                'slug' => 'compress-pdf',
                'description' => 'Reduce PDF file size while maintaining quality.',
                'metaTitle' => 'Compress PDF - KortexTools',
                'metaDescription' => 'Reduce PDF file size while maintaining quality.',
                'popularity' => 88,
                'rating' => 4.6,
                'rating_count' => 175,
            ],
            [
                'icon' => 'fas fa-lock',
                'name' => 'Protect PDF',
                'slug' => 'protect-pdf',
                'description' => 'Encrypt PDF files with a password.',
                'metaTitle' => 'Protect PDF - KortexTools',
                'metaDescription' => 'Encrypt PDF files with a password.',
                'popularity' => 85,
                'rating' => 4.5,
                'rating_count' => 152,
            ],
            [
                'icon' => 'fas fa-unlock',
                'name' => 'Unlock PDF',
                'slug' => 'unlock-pdf',
                'description' => 'Remove password protection from a PDF file.',
                'metaTitle' => 'Unlock PDF - KortexTools',
                'metaDescription' => 'Remove password protection from a PDF file.',
                'popularity' => 82,
                'rating' => 4.4,
                'rating_count' => 128,
            ],
        ],

        'File Conversion' => [
            [
                'icon' => 'fas fa-file-word',
                'name' => 'Word to PDF',
                'slug' => 'word-to-pdf',
                'description' => 'Convert Word (DOC, DOCX) documents to PDF easily.',
                'metaTitle' => 'Word to PDF - KortexTools',
                'metaDescription' => 'Convert Word (DOC, DOCX) documents to PDF easily.',
                'popularity' => 92,
                'rating' => 4.7,
                'rating_count' => 213,
            ],
            [
                'icon' => 'fas fa-file-powerpoint',
                'name' => 'PowerPoint to PDF',
                'slug' => 'powerpoint-to-pdf',
                'description' => 'Convert PowerPoint (PPT, PPTX) presentations to PDF easily.',
                'metaTitle' => 'PowerPoint to PDF - KortexTools',
                'metaDescription' => 'Convert PowerPoint (PPT, PPTX) presentations to PDF easily.',
                'popularity' => 87,
                'rating' => 4.6,
                'rating_count' => 189,
            ],
            [
                'icon' => 'fas fa-file-excel',
                'name' => 'Excel to PDF',
                'slug' => 'excel-to-pdf',
                'description' => 'Convert Excel (XLS, XLSX) spreadsheets into PDF documents.',
                'metaTitle' => 'Excel to PDF - KortexTools',
                'metaDescription' => 'Convert Excel (XLS, XLSX) spreadsheets into PDF documents.',
                'popularity' => 84,
                'rating' => 4.5,
                'rating_count' => 167,
            ],
            [
                'icon' => 'fas fa-images',
                'name' => 'JPG to PDF',
                'slug' => 'jpg-to-pdf',
                'description' => 'Convert JPG images into a single PDF file.',
                'metaTitle' => 'JPG to PDF - KortexTools',
                'metaDescription' => 'Convert JPG images into a single PDF file.',
                'popularity' => 86,
                'rating' => 4.6,
                'rating_count' => 195,
            ],
            [
                'icon' => 'fas fa-file-pdf',
                'name' => 'PDF to Excel',
                'slug' => 'pdf-to-excel',
                'description' => 'Convert PDF files into editable Excel spreadsheets.',
                'metaTitle' => 'PDF to Excel - KortexTools',
                'metaDescription' => 'Convert PDF files into editable Excel spreadsheets.',
                'popularity' => 80,
                'rating' => 4.4,
                'rating_count' => 142,
            ],
        ],

        'Developer Tools' => [
            [
                'icon' => 'fas fa-file-code',
                'name' => 'JSON Formatter',
                'slug' => 'json-formatter',
                'description' => 'Beautify and validate JSON data with syntax highlighting.',
                'metaTitle' => 'JSON Formatter - KortexTools',
                'metaDescription' => 'Beautify and validate JSON data with syntax highlighting.',
                'popularity' => 93,
                'rating' => 4.8,
                'rating_count' => 267,
            ],
            [
                'icon' => 'fas fa-lock',
                'name' => 'Base64 Encoder',
                'slug' => 'encode',
                'description' => 'Encode text and files to Base64 format.',
                'metaTitle' => 'Base64 Encoder - KortexTools',
                'metaDescription' => 'Encode text and files to Base64 format.',
                'popularity' => 89,
                'rating' => 4.7,
                'rating_count' => 211,
            ],
            [
                'icon' => 'fas fa-unlock',
                'name' => 'Base64 Decoder',
                'slug' => 'decode',
                'description' => 'Decode Base64 encoded text and files.',
                'metaTitle' => 'Base64 Decoder - KortexTools',
                'metaDescription' => 'Decode Base64 encoded text and files.',
                'popularity' => 88,
                'rating' => 4.7,
                'rating_count' => 203,
            ],
            [
                'icon' => 'fas fa-key',
                'name' => 'JWT Encoder/Decoder',
                'slug' => 'jwt-encoder-decoder',
                'description' => 'Encode, decode, and verify JSON Web Tokens easily.',
                'metaTitle' => 'JWT Encoder/Decoder - KortexTools',
                'metaDescription' => 'Encode, decode, and verify JSON Web Tokens easily.',
                'popularity' => 85,
                'rating' => 4.6,
                'rating_count' => 178,
            ],
            [
                'icon' => 'fas fa-hashtag',
                'name' => 'Hash Generator',
                'slug' => 'hash',
                'description' => 'Generate MD5, SHA256, and SHA512 hashes.',
                'metaTitle' => 'Hash Generator - KortexTools',
                'metaDescription' => 'Generate MD5, SHA256, and SHA512 hashes.',
                'popularity' => 87,
                'rating' => 4.6,
                'rating_count' => 192,
            ],
            [
                'icon' => 'fas fa-shield-alt',
                'name' => 'SSL Certificate Checker',
                'slug' => 'ssl-checker',
                'description' => 'Check SSL certificate validity, security, and expiration dates.',
                'metaTitle' => 'SSL Certificate Checker - KortexTools',
                'metaDescription' => 'Check SSL certificate validity, security, and expiration dates for any website.',
                'popularity' => 82,
                'rating' => 4.5,
                'rating_count' => 164,
            ],
            [
                'icon' => 'fas fa-unlink',
                'name' => 'Broken Links Checker',
                'slug' => 'websites-broken-link-checker',
                'description' => 'Find and check broken links on any website for better SEO.',
                'metaTitle' => 'Broken Links Checker - KortexTools',
                'metaDescription' => 'Find and fix broken links on your website to improve SEO and user experience.',
                'popularity' => 79,
                'rating' => 4.4,
                'rating_count' => 147,
            ],
            [
                'icon' => 'fas fa-camera',
                'name' => 'Website Screenshot',
                'slug' => 'website-screenshot-generator',
                'description' => 'Capture high-quality screenshots of any website.',
                'metaTitle' => 'Website Screenshot Generator - KortexTools',
                'metaDescription' => 'Generate high-quality screenshots of any website for previews and documentation.',
                'popularity' => 76,
                'rating' => 4.3,
                'rating_count' => 133,
            ],
            [
                'icon' => 'fas fa-search-plus',
                'name' => 'DNS Lookup',
                'slug' => 'dns-lookup',
                'description' => 'Find all DNS records for any domain including A, MX, NS, and TXT records.',
                'metaTitle' => 'DNS Lookup Tool - KortexTools',
                'metaDescription' => 'Perform comprehensive DNS lookups to find A, AAAA, CNAME, MX, NS, TXT, and SOA records.',
                'popularity' => 74,
                'rating' => 4.2,
                'rating_count' => 119,
            ],
            [
                'icon' => 'fas fa-eye',
                'name' => 'HTTP Header Viewer',
                'slug' => 'http-header-viewer',
                'description' => 'View and analyze HTTP response headers and security configuration.',
                'metaTitle' => 'HTTP Header Viewer - KortexTools',
                'metaDescription' => 'View HTTP response headers and analyze website security configuration.',
                'popularity' => 71,
                'rating' => 4.1,
                'rating_count' => 107,
            ],
        ],

        'Image Tools' => [
            [
                'icon' => 'fas fa-image',
                'name' => 'Image Compressor',
                'slug' => 'image-compressor',
                'description' => 'Compress and optimize images for web use.',
                'metaTitle' => 'Image Compressor - KortexTools',
                'metaDescription' => 'Compress and optimize images for web use.',
                'popularity' => 91,
                'rating' => 4.7,
                'rating_count' => 234,
            ],
            [
                'icon' => 'fas fa-file-image',
                'name' => 'Image Converter',
                'slug' => 'image-converter',
                'description' => 'Convert images between PNG, JPG, WebP, and more.',
                'metaTitle' => 'Image Converter - KortexTools',
                'metaDescription' => 'Convert images between PNG, JPG, WebP, and more.',
                'popularity' => 89,
                'rating' => 4.6,
                'rating_count' => 218,
            ],
            [
                'icon' => 'fas fa-qrcode',
                'name' => 'QR Code Generator',
                'slug' => 'qrcode',
                'description' => 'Generate QR codes from text, URLs, and more.',
                'metaTitle' => 'QR Code Generator - KortexTools',
                'metaDescription' => 'Generate QR codes from text, URLs, and more.',
                'popularity' => 90,
                'rating' => 4.8,
                'rating_count' => 251,
            ],
            [
                'icon' => 'fas fa-bg',
                'name' => 'Background Remover',
                'slug' => 'image-background',
                'description' => 'Remove background from images automatically.',
                'metaTitle' => 'Background Remover - KortexTools',
                'metaDescription' => 'Remove background from images automatically.',
                'popularity' => 88,
                'rating' => 4.7,
                'rating_count' => 206,
            ],
            [
                'icon' => 'fas fa-palette',
                'name' => 'Color Converter',
                'slug' => 'color-converter',
                'description' => 'Convert between HEX, RGB, HSL color formats.',
                'metaTitle' => 'Color Converter - KortexTools',
                'metaDescription' => 'Convert between HEX, RGB, HSL color formats.',
                'popularity' => 82,
                'rating' => 4.5,
                'rating_count' => 167,
            ],
        ],

        'Text Tools' => [
            [
                'icon' => 'fas fa-font',
                'name' => 'Text Case Converter',
                'slug' => 'text-case',
                'description' => 'Convert text between UPPERCASE, lowercase, Title Case, and more.',
                'metaTitle' => 'Text Case Converter - KortexTools',
                'metaDescription' => 'Convert text between UPPERCASE, lowercase, Title Case, and more.',
                'popularity' => 84,
                'rating' => 4.5,
                'rating_count' => 174,
            ],
            [
                'icon' => 'fas fa-ruler',
                'name' => 'Character Counter',
                'slug' => 'character-counter',
                'description' => 'Count characters, words, sentences, and paragraphs.',
                'metaTitle' => 'Character Counter - KortexTools',
                'metaDescription' => 'Count characters, words, sentences, and paragraphs.',
                'popularity' => 81,
                'rating' => 4.4,
                'rating_count' => 151,
            ],
            [
                'icon' => 'fas fa-link',
                'name' => 'URL Slug Generator',
                'slug' => 'slugify',
                'description' => 'Convert text to URL-friendly slugs.',
                'metaTitle' => 'URL Slug Generator - KortexTools',
                'metaDescription' => 'Convert text to URL-friendly slugs.',
                'popularity' => 79,
                'rating' => 4.3,
                'rating_count' => 138,
            ],
            [
                'icon' => 'fas fa-dice',
                'name' => 'Password Generator',
                'slug' => 'password-generator',
                'description' => 'Generate secure random passwords.',
                'metaTitle' => 'Password Generator - KortexTools',
                'metaDescription' => 'Generate secure random passwords.',
                'popularity' => 86,
                'rating' => 4.6,
                'rating_count' => 187,
            ],
            [
                'icon' => 'fas fa-stream',
                'name' => 'Lorem Ipsum Generator',
                'slug' => 'lorem-ipsum',
                'description' => 'Generate Lorem Ipsum placeholder text.',
                'metaTitle' => 'Lorem Ipsum Generator - KortexTools',
                'metaDescription' => 'Generate Lorem Ipsum placeholder text.',
                'popularity' => 75,
                'rating' => 4.2,
                'rating_count' => 118,
            ],
        ],

        'Utilities' => [
            [
                'icon' => 'fas fa-network-wired',
                'name' => 'IP Address Info',
                'slug' => 'current-ip-info',
                'description' => 'Get detailed information about an IP address.',
                'metaTitle' => 'IP Address Info - KortexTools',
                'metaDescription' => 'Get detailed information about an IP address.',
                'popularity' => 80,
                'rating' => 4.4,
                'rating_count' => 156,
            ],
            [
                'icon' => 'fas fa-globe',
                'name' => 'WHOIS Lookup',
                'slug' => 'whois-lookup',
                'description' => 'Look up WHOIS information for domain names.',
                'metaTitle' => 'WHOIS Lookup - KortexTools',
                'metaDescription' => 'Look up WHOIS information for domain names.',
                'popularity' => 78,
                'rating' => 4.3,
                'rating_count' => 145,
            ],
            [
                'icon' => 'fas fa-link-slash',
                'name' => 'URL Extractor',
                'slug' => 'url-extractor',
                'description' => 'Extract all URLs from text or HTML.',
                'metaTitle' => 'URL Extractor - KortexTools',
                'metaDescription' => 'Extract all URLs from text or HTML.',
                'popularity' => 72,
                'rating' => 4.2,
                'rating_count' => 128,
            ],
            [
                'icon' => 'fas fa-clock',
                'name' => 'Unix Timestamp Converter',
                'slug' => 'timestamp-converter',
                'description' => 'Convert between Unix timestamps and readable dates.',
                'metaTitle' => 'Unix Timestamp Converter - KortexTools',
                'metaDescription' => 'Convert between Unix timestamps and readable dates.',
                'popularity' => 83,
                'rating' => 4.5,
                'rating_count' => 169,
            ],
            [
                'icon' => 'fas fa-id-card',
                'name' => 'UUID Generator',
                'slug' => 'uuid-generator',
                'description' => 'Generate random UUIDs.',
                'metaTitle' => 'UUID Generator - KortexTools',
                'metaDescription' => 'Generate random UUIDs.',
                'popularity' => 74,
                'rating' => 4.3,
                'rating_count' => 135,
            ],
            [
                'icon' => 'fas fa-calendar-alt',
                'name' => 'Domain Age Checker',
                'slug' => 'domain-age-checker',
                'description' => 'Check domain registration date and age for SEO analysis.',
                'metaTitle' => 'Domain Age Checker - KortexTools',
                'metaDescription' => 'Check domain registration date, age, and trust metrics for SEO analysis.',
                'popularity' => 73,
                'rating' => 4.2,
                'rating_count' => 129,
            ],
            [
                'icon' => 'fas fa-map-marker-alt',
                'name' => 'Fake Address Generator',
                'slug' => 'fake-address-generator',
                'description' => 'Generate realistic fake addresses for testing from multiple countries.',
                'metaTitle' => 'Fake Address Generator - KortexTools',
                'metaDescription' => 'Generate realistic fake addresses for testing and development purposes.',
                'popularity' => 69,
                'rating' => 4.0,
                'rating_count' => 95,
            ],
        ],
    ]
];
