<?php

namespace App\Services\Kortextools\Handlers;

class ToolHandlerFactory
{
    /**
     * Map of tool slugs to handler classes
     */
    private static $handlers = [
        'pdf-merge' => PdfMergeHandler::class,
        'split-pdf' => 'App\\Services\\Kortextools\\Handlers\\PdfSplitterHandler',
        'compress-pdf' => PdfCompressorHandler::class,
        'protect-pdf' => 'App\\Services\\Kortextools\\Handlers\\PdfProtectHandler',
        'unlock-pdf' => PdfUnlockHandler::class,
        'word-to-pdf' => WordToPdfHandler::class,
        'powerpoint-to-pdf' => PowerPointToPdfHandler::class,
        'excel-to-pdf' => ExcelToPdfHandler::class,
        'jpg-to-pdf' => JpgToPdfHandler::class,
        'pdf-to-excel' => PdfToExcelHandler::class,
        'json-formatter' => JsonFormatterHandler::class,
        'encode' => Base64EncodeHandler::class,
        'decode' => Base64DecodeHandler::class,
        'jwt-encoder-decoder' => JwtDecoderHandler::class,
        'jwt-decoder' => JwtDecoderHandler::class,
        'hash' => HashGeneratorHandler::class,
        'hash-generator' => HashGeneratorHandler::class,
        'regex-tester' => RegexTesterHandler::class,
        'markdown-to-html' => MarkdownToHtmlHandler::class,
        'image-compressor' => ImageCompressorHandler::class,
        'image-converter' => ImageConverterHandler::class,
        'qrcode' => QrCodeGeneratorHandler::class,
        'image-background' => BackgroundRemoverHandler::class,
        'color-converter' => ColorConverterHandler::class,
        'text-case' => TextCaseHandler::class,
        'character-counter' => CharacterCounterHandler::class,
        'slug-generator' => SlugifyHandler::class,
        'slugify' => SlugGenHandler::class,
        'password-generator' => PasswordGeneratorHandler::class,
        'url-encode' => UrlEncodeHandler::class,
        'uuid-generator' => UuidGeneratorHandler::class,
        'timestamp-converter' => TimestampConverterHandler::class,
        'lorem-ipsum' => LoremIpsumHandler::class,
        'ip-info' => IpInfoHandler::class,
        'current-ip-info' => IpInfoHandler::class,
        'whois-lookup' => WhoisLookupHandler::class,
        'url-extractor' => UrlExtractorHandler::class,
        'age-calculator' => AgeCalculatorHandler::class,
        'percentage-calculator' => PercentageCalculatorHandler::class,
        'average-calculator' => AverageCalculatorHandler::class,
        'reverse-text' => ReverseTextHandler::class,
        'password-strength-checker' => PasswordStrengthCheckerHandler::class,
        'rgb-to-hex' => RgbToHexHandler::class,
        'text-to-binary' => TextToBinaryHandler::class,
        'binary-to-text' => BinaryToTextHandler::class,
        'text-to-ascii' => TextToAsciiHandler::class,
        'email-validator' => EmailValidatorHandler::class,
        'word-counter' => WordCounterHandler::class,
        'discount-calculator' => DiscountCalculatorHandler::class,
        'decimal-to-hex' => DecimalToHexHandler::class,
        'temperature-converter' => TemperatureConverterHandler::class,
        'weight-converter' => WeightConverterHandler::class,
        'length-converter' => LengthConverterHandler::class,
        'area-converter' => AreaConverterHandler::class,
        'volume-converter' => VolumeConverterHandler::class,
        'speed-converter' => SpeedConverterHandler::class,
        'power-converter' => PowerConverterHandler::class,
        'pressure-converter' => PressureConverterHandler::class,
        'byte-converter' => ByteConverterHandler::class,
        'time-converter' => TimeConverterHandler::class,
        'torque-converter' => TorqueConverterHandler::class,
        'random-number-generator' => RandomNumberGeneratorHandler::class,
        'lorem-ipsum-generator' => LoremIpsumGeneratorHandler::class,
        'fake-credit-card-generator' => FakeCreditCardGeneratorHandler::class,
        'case-converter' => CaseConverterHandler::class,
        'base64-encoder-decoder' => Base64EncoderDecoderHandler::class,
        'url-encoder-decoder' => UrlEncoderDecoderHandler::class,
        'small-text-generator' => SmallTextGeneratorHandler::class,
        'json-validator' => JsonValidatorHandler::class,
        'xml-validator' => XmlValidatorHandler::class,
        'url-validator' => UrlValidatorHandler::class,
        'image-resizer' => ImageResizerHandler::class,
        'webp-converter' => WebpConverterHandler::class,
        'favicon-generator' => FaviconGeneratorHandler::class,
        'png-to-jpg' => PngToJpgConverterHandler::class,
        'pdf-merger' => PdfMergerHandler::class,
        'pdf-splitter' => PdfSplitterHandler::class,
        'pdf-compressor' => PdfCompressorHandler::class,
        'pdf-protect' => PdfProtectHandler::class,
        'pdf-unlock' => PdfUnlockHandler::class,
        'domain-validator' => DomainValidatorHandler::class,
        'ip-validator' => IpAddressValidatorHandler::class,
        'phone-validator' => PhoneValidatorHandler::class,
        'isbn-validator' => IsbnValidatorHandler::class,
        'iban-validator' => IbanValidatorHandler::class,
        'ping-tool' => PingToolHandler::class,
        'fake-name-generator' => FakeNameGeneratorHandler::class,
        'csv-to-json' => CsvToJsonHandler::class,
        'json-to-csv' => JsonToCsvHandler::class,
        'bmi-calculator' => BmiCalcHandler::class,
        'age-calculator' => AgeCalcHandler::class,
        'md5-hash' => Md5HashGenHandler::class,
        'sha256-hash' => Sha256HashGenHandler::class,
        'hmac-generator' => HmacGenHandler::class,
        'slug-generator' => SlugGenHandler::class,
        'reverse-text' => ReverseTextHandlerImpl::class,
        'regex-tester' => RegexTestHandler::class,
        'rgb-to-hex' => RgbToHexHandlerImpl::class,
        'hex-to-rgb' => HexToRgbHandler::class,
        'utm-builder' => UtmBuilderHandler::class,
        'ssl-checker' => SslCheckerHandler::class,
        'dns-lookup' => DnsLookupHandler::class,
        'port-checker' => GenericToolHandler::class,
        'http-header-viewer' => HttpHeaderViewerHandler::class,
        'fake-address-generator' => FakeAddressGeneratorHandler::class,
        'fake-email-generator' => GenericToolHandler::class,
        'qr-code-generator' => GenericToolHandler::class,
        'barcode-generator' => GenericToolHandler::class,
        'json-to-yaml' => GenericToolHandler::class,
        'xml-to-json' => GenericToolHandler::class,
        'markdown-to-html' => GenericToolHandler::class,
        'word-counter' => GenericToolHandler::class,
        'character-counter' => GenericToolHandler::class,
        'line-counter' => GenericToolHandler::class,
        'text-diff-checker' => GenericToolHandler::class,
        'palindrome-checker' => GenericToolHandler::class,
        'utf8-encoder' => GenericToolHandler::class,
        'morse-code-converter' => GenericToolHandler::class,
        'caesar-cipher' => GenericToolHandler::class,
        'rot13-converter' => GenericToolHandler::class,
        'atbash-cipher' => GenericToolHandler::class,
        'zip-creator' => GenericToolHandler::class,
        'zip-extractor' => GenericToolHandler::class,
        'rar-extractor' => GenericToolHandler::class,
        'gzip-compressor' => GenericToolHandler::class,
        'gzip-decompressor' => GenericToolHandler::class,
        'crc32-checksum' => GenericToolHandler::class,
        'meta-tag-generator' => GenericToolHandler::class,
        'robots-txt-generator' => GenericToolHandler::class,
        'sitemap-generator' => GenericToolHandler::class,
        'open-graph-generator' => GenericToolHandler::class,
        'twitter-card-generator' => GenericToolHandler::class,
        'hashtag-generator' => GenericToolHandler::class,
        'url-shortener-simulator' => GenericToolHandler::class,
        'html-minifier' => GenericToolHandler::class,
        'css-minifier' => GenericToolHandler::class,
        'javascript-minifier' => GenericToolHandler::class,
        'sql-formatter' => GenericToolHandler::class,
        'api-mock-response' => GenericToolHandler::class,
        'loan-calculator' => GenericToolHandler::class,
        'tax-calculator' => GenericToolHandler::class,
        'tip-calculator' => GenericToolHandler::class,
        'timezone-converter' => GenericToolHandler::class,
        'number-base-converter' => GenericToolHandler::class,
        'roman-numeral-converter' => GenericToolHandler::class,
        'color-palette-generator' => GenericToolHandler::class,
        'social-share-meta' => GenericToolHandler::class,
        'google-analytics-generator' => GenericToolHandler::class,
        'pixel-tracker-generator' => GenericToolHandler::class,
        // Database migrated tools
        'adsense-calculator' => GenericToolHandler::class,
        'area-converter' => GenericToolHandler::class,
        'ascii-to-binary' => GenericToolHandler::class,
        'avif-to-jpg' => GenericToolHandler::class,
        'avif-to-png' => GenericToolHandler::class,
        'base64-encode-decode' => GenericToolHandler::class,
        'bilibili-video-downloader' => GenericToolHandler::class,
        'binary-to-ascii' => GenericToolHandler::class,
        'binary-to-decimal' => GenericToolHandler::class,
        'binary-to-hex' => GenericToolHandler::class,
        'blacklist-check' => GenericToolHandler::class,
        'bmp-to-pdf' => GenericToolHandler::class,
        'check-gzip-compression' => GenericToolHandler::class,
        'comma-separator' => GenericToolHandler::class,
        'credit-card-generator' => GenericToolHandler::class,
        'dailymotion-video-downloader' => GenericToolHandler::class,
        'decimal-to-binary' => GenericToolHandler::class,
        'domain-age-checker' => DomainAgeCheckerHandler::class,
        'domain-authority-checker' => GenericToolHandler::class,
        'domain-hosting-checker' => GenericToolHandler::class,
        'domain-name-search' => GenericToolHandler::class,
        'domain-to-api' => GenericToolHandler::class,
        'english-converter' => GenericToolHandler::class,
        'find-dns-record' => GenericToolHandler::class,
        'get-http-headers' => GenericToolHandler::class,
        'gif-to-pdf' => GenericToolHandler::class,
        'google-cache-checker' => GenericToolHandler::class,
        'grayscale-pdf' => GenericToolHandler::class,
        'heic-to-jpg' => GenericToolHandler::class,
        'heic-to-png' => GenericToolHandler::class,
        'hex-to-binary' => GenericToolHandler::class,
        'htaccess-redirect' => GenericToolHandler::class,
        'html-editor' => GenericToolHandler::class,
        'html-to-pdf' => GenericToolHandler::class,
        'html-viewer' => GenericToolHandler::class,
        'image-to-pdf' => GenericToolHandler::class,
        'image-to-text-converter' => GenericToolHandler::class,
        'ip-location' => GenericToolHandler::class,
        'jpg-converter' => GenericToolHandler::class,
        'jpg-to-svg' => GenericToolHandler::class,
        'jpg-to-word' => GenericToolHandler::class,
        'js-minifier' => GenericToolHandler::class,
        'json-beautifier' => GenericToolHandler::class,
        'json-editor' => GenericToolHandler::class,
        'json-to-xml' => GenericToolHandler::class,
        'json-viewer' => GenericToolHandler::class,
        'keyword-density-checker' => GenericToolHandler::class,
        'keyword-position' => GenericToolHandler::class,
        'keyword-research-tool' => GenericToolHandler::class,
        'keywords-rich-domains' => GenericToolHandler::class,
        'lock-pdf' => GenericToolHandler::class,
        'md5-generator' => GenericToolHandler::class,
        'meme-generator' => GenericToolHandler::class,
        'merge-pdf' => GenericToolHandler::class,
        'meta-tag-analyzer' => GenericToolHandler::class,
        'mobile-friendly-test' => GenericToolHandler::class,
        'mozrank-checker' => GenericToolHandler::class,
        'number-generator' => GenericToolHandler::class,
        'online-text-editor' => GenericToolHandler::class,
        'organize-pdf' => GenericToolHandler::class,
        'paraphrased' => ParaphrasedHandler::class,
        'pdf-to-bmp' => GenericToolHandler::class,
        'pdf-to-jpg' => GenericToolHandler::class,
        'pdf-to-png' => GenericToolHandler::class,
        'pdf-to-powerpoint' => GenericToolHandler::class,
        'pdf-to-tiff' => GenericToolHandler::class,
        'pdf-to-word' => GenericToolHandler::class,
        'pdf-to-zip' => GenericToolHandler::class,
        'png-to-pdf' => GenericToolHandler::class,
        'png-to-svg' => GenericToolHandler::class,
        'png-to-webp' => GenericToolHandler::class,
        'ppt-to-pdf' => GenericToolHandler::class,
        'probability-calculator' => GenericToolHandler::class,
        'related-keywords-finder' => GenericToolHandler::class,
        'remove-pdf-pages' => GenericToolHandler::class,
        'reverse-image-search' => GenericToolHandler::class,
        'reverse-text-generator' => GenericToolHandler::class,
        'rewrite-article' => RewriteArticleHandler::class,
        'sales-tax-calculator' => GenericToolHandler::class,
        'seo-report' => GenericToolHandler::class,
        'serp-checker' => GenericToolHandler::class,
        'spider-simulator' => GenericToolHandler::class,
        'svg-converter' => GenericToolHandler::class,
        'svg-to-jpg' => GenericToolHandler::class,
        'svg-to-png' => GenericToolHandler::class,
        'tag-generator' => GenericToolHandler::class,
        'text-image' => GenericToolHandler::class,
        'text-pdf-converter' => GenericToolHandler::class,
        'tiff-to-pdf' => GenericToolHandler::class,
        'url-encode-decode' => GenericToolHandler::class,
        'url-opener' => GenericToolHandler::class,
        'video-to-gif' => GenericToolHandler::class,
        'voltage-converter' => GenericToolHandler::class,
        'watermark-pdf' => GenericToolHandler::class,
        'webp-to-png' => GenericToolHandler::class,
        'webpage-screen-resultion-simulator' => GenericToolHandler::class,
        'website-screenshot-generator' => WebsiteScreenshotHandler::class,
        'websites-broken-link-checker' => BrokenLinksCheckerHandler::class,
        'what-is-my-browser' => GenericToolHandler::class,
        'what-is-my-ip' => GenericToolHandler::class,
        'word-combiner' => GenericToolHandler::class,
        'word-pdf-converter' => GenericToolHandler::class,
        'wordpress-password-generator' => GenericToolHandler::class,
        'wordpress-theme-detector' => GenericToolHandler::class,
        'xml-formatter' => GenericToolHandler::class,
        'xml-json' => GenericToolHandler::class,
        'xml-sitemap-generator' => GenericToolHandler::class,
    ];

    /**
     * Get handler for a tool
     *
     * @param string $toolSlug
     * @return ToolHandlerInterface|null
     */
    public static function getHandler($toolSlug)
    {
        if (!isset(self::$handlers[$toolSlug])) {
            return null;
        }

        $handlerClass = self::$handlers[$toolSlug];

        if (!class_exists($handlerClass)) {
            return null;
        }

        return new $handlerClass();
    }

    /**
     * Check if handler exists for a tool
     *
     * @param string $toolSlug
     * @return bool
     */
    public static function hasHandler($toolSlug)
    {
        return isset(self::$handlers[$toolSlug]) && class_exists(self::$handlers[$toolSlug]);
    }

    /**
     * Get all registered tool slugs
     *
     * @return array
     */
    public function getRegisteredTools()
    {
        return array_keys(self::$handlers);
    }
}
